---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by BLUGTHEK.
--- DateTime: 9/11/2022 9:16 PM
---

local ESX = nil

Citizen.CreateThread(function()
	while ESX == nil do
		Citizen.Wait(0)
		TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
	end

	while ESX.GetPlayerData().job == nil do
		Citizen.Wait(100)
	end

	while tempDataStorage.CurrentJob == nil do
		ESX.PlayerData = ESX.GetPlayerData()
		tempDataStorage.CurrentJob = ESX.PlayerData.job.name
	end

	while true do
		Citizen.Wait(10000)
		ESX.PlayerData = ESX.GetPlayerData()
		tempDataStorage.CurrentJob = ESX.PlayerData.job.name
	end
end)

Citizen.CreateThread(function()
	local timer = 1000
	while true do
		Citizen.Wait(timer)
		local coords = GetEntityCoords(PlayerPedId())
		for k,v in pairs(Config.Vault) do
			local dist = GetDistanceBetweenCoords(coords, v.coords, true)
			if dist < v.dist and tempDataStorage.CurrentJob == v.job then
				timer = 0
				ESX.ShowHelpNotification('<font face="font4thai">กด [~r~E~w~] เพื่อเปิดตู้</font>')

				if IsControlJustReleased(0, 38) then
					OpenVaultInventoryMenu(v.sqlQuery)
				else
					break
				end
			else
				timer = 1000
			end
		end
	end
end)

function OpenVaultInventoryMenu(society)
	ESX.TriggerServerCallback(
			"blugx:fetchVaultItem",
			function(inventory)
				if not inventory then
					TriggerEvent('blug_ext:SendNotification',{
						description = 'คุณไม่มีสิทธิ์เข้าถึง!',
						type = 'error'
					})
				else
					TriggerEvent("monster_inventoryhud:openVaultInventory", inventory)
				end
			end,
			false,society
	)
end